version: '3'
services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads         # Чтобы загрузки сохранились между перезапусками
      - ./chroma_db:/app/chroma_db   # Чтобы данные в базе не исчезали
    environment:
      - PYTHONUNBUFFERED=1